package services;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import sala.patryk.projekt.wypozyczalniavideo.Customer;

public class CustomerDBManager {

	private Connection conn;

	private Statement stmt;

	private PreparedStatement addcustomerStmt;
	private PreparedStatement getcustomersStmt;


	public CustomerDBManager ()
	{
	try {
	conn= DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");

	stmt=conn.createStatement();
	boolean customerTableExists=false;

	ResultSet rs= conn.getMetaData().getTables(null, null, null, null);

	while(rs.next())
	{
	if("customer".equalsIgnoreCase(rs.getString("TABLE_NAME")))
	{
	customerTableExists=true;
	break;
	}
	}


	if(!customerTableExists)
	{
	stmt.executeUpdate("" +
	"CREATE TABLE customer(" +
	"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
	"name varchar(20)," +
	"" +
	")");
	}

	addcustomerStmt=conn.prepareStatement("" +
	"INSERT INTO customer (name) VALUES (?)" +
	"");

	getcustomersStmt=conn.prepareStatement("" +
	"SELECT * FROM customer" +
	"");



	} catch (SQLException e) {

	e.printStackTrace();
	}
	}

	public void addCustomer(Customer p)
	{
	try {
	addcustomerStmt.setString(1, p.getName());

	addcustomerStmt.executeUpdate();

	} catch (SQLException e) {

	e.printStackTrace();
	}

	}

	public List<Customer> getAllcustomers()
	{
	List<Customer> customers=new ArrayList<Customer>();

	try {
	ResultSet rs= getcustomersStmt.executeQuery();

	while(rs.next())
	{
	customers.add(new Customer(rs.getString("name")));
	}

	} catch (SQLException e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
	}

	return customers;
	}


	}


	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
}
